apiVersion: v1
entries:
  bc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-04T18:22:27.16583331Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 316823dad916b041db2e4db27e6428537a0c14a90e1313f8db18dad6cbaa6c81
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bc
    urls:
    - bc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-04T18:22:27.16245001Z"
