apiVersion: v1
entries:
  bc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-17T14:08:58.9125097Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: fa72869c1ec9dbed68a38138b547128be9cfb89fbea7a65d69b0d47ff1b0f41d
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bc
    urls:
    - bc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-17T14:08:58.9049146Z"
